#!/usr/bin/with-contenv sh

if [ -z "$DEVTOOLS_PRIVATE_KEY" ]; then
  echo "DEVTOOLS_PRIVATE_KEY is not set. You will not be able to clone private repositories."
  exit  
fi

echo 
echo "DEVTOOLS_PRIVATE_KEY exists. Setting up private key..."

mkdir /root/.ssh

if [[ "$DEVTOOLS_PRIVATE_KEY" =~ "BEGIN DSA" ]]; then
    KEY_NAME="id_dsa"
elif [[ "$DEVTOOLS_PRIVATE_KEY" =~ "BEGIN RSA" ]]; then
    KEY_NAME="id_rsa"
else
  echo "Private key is not DSA or RSA format."
  exit
fi	


echo "$DEVTOOLS_PRIVATE_KEY" > /root/.ssh/$KEY_NAME
chmod 600 /root/.ssh/$KEY_NAME

ssh-keyscan -H bitbucket.org >> /root/.ssh/known_hosts
ssh-keyscan -H github.com >> /root/.ssh/known_hosts

